### ISSUE TITLE
Adguard no longer blocks ads on Twitch 

### ISSUE THREAD

**Issue by Samuxle** [AdguardTeam/AdGuardExtra#475]
### Prerequisites

- [X] Filters were updated before reproducing an issue;
- [X] AdGuard Extra version is up-to-date;

### What product do you use?

AdGuard for Android

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

other (specify in comment below)

### Where is the problem encountered?

Twitch.tv

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard Dutch filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, AdGuard Turkish filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter, AdGuard Experimental filter, Filter unblocking search ads and self-promotion, ---Third-party filters---, EasyList, ABPindo, Bulgarian list, EasyList China, EasyList Czech and Slovak, EasyList Dutch, EasyList Germany, EasyList Hebrew, EasyList Italy, EasyList Lithuania, Latvian List, Liste AR, Liste FR, ROList, EasyPrivacy, Icelandic ABP List, AdBlockID, Greek AdBlock Filter, Fanboy's Annoyances, Fanboy's Social Blocking List, Web Annoyances Ultralist, Thai Ads Filters, Hungarian filter, Peter Lowe's Blocklist, Xfiles, Adblock Warning Removal List, Online Malicious URL Blocklist, RU AdList - Counters, ABPVN List, Fanboy's Enhanced Tracking List, Official Polish filters for AdBlock, uBlock Origin & AdGuard, Polish GDPR-Cookies Filters, Estonian List, CJX's Annoyances List, Polish Social Filters, Fanboy's Anti-Facebook List, List-KR, xinggsf, I don't care about cookies, EasyList Spanish, KAD - Anti-Scam, Adblock List for Finland, ROLIST2, Iranian filter, road-block, Polish Annoyances Filters, Polish Anti Adblock Filters, Fanboy's Anti-thirdparty Fonts, EasyList Cookie List, NoCoin Filter List, Frellwit's Swedish Filter, YousList, AlleBlock, EasyList Polish, Polish Anti-Annoying Special Supplement, Dandelion Sprout's Nordic Filters, Dandelion Sprout's Annoyances List, Dandelion Sprout's Serbo-Croatian List, IndianList

### Add your comment and screenshots

Until a few days ago, Adguard also blocked ads on the Twitch app but since yesterday it no longer does so

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/166522

**Comment by stanislav-atr** [comment]
@Samuxle, hi! AdGuard Extra is not applicable to mobile apps. It seems to me that this issue was resolved with filters.

**Comment by Brando813** [comment]
Hello, this issue has still not been resolved since I opened it a few weeks ago.  Updating filters does not solve it and ads play on both the Twitch site and app with Adguard enabled.
