### ISSUE TITLE
Ads on twitch again

### ISSUE THREAD

**Issue by leashadav** [AdguardTeam/AdGuardExtra#602]
### Prerequisites

- [x] Filters were updated before reproducing an issue
- [x] AdGuard Extra version is up-to-date
- [x] I checked to make sure that this issue has not already been filed

### What product do you use?

AdGuard Extra Extension

### What type of problem have you encountered?

Missed ads or ad leftovers

### Which browser(s) do you use?

other (specify in comment below)

### Where is the problem encountered?

https://www.twitch.tv/goldiepanda93 https://www.twitch.tv/princesadhanaazola https://www.twitch.tv/vi_valkyrie https://www.twitch.tv/miakurimu

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Steps to reproduce:
1. open twitch
2. go to any streamer
3. wait and ads start playing

### Expected Behavior

It seems twitch updated or something, the past week i had to switch the extention to on click for it to stop ads, otherwise they kept popping up, now today even on click does not stop the ads. I removed the extention and readded it hoping it would help, no luck, still getting ads.

### Actual Behavior

It seems twitch updated or something, the past week i had to switch the extention to on click for it to stop ads, otherwise they kept popping up, now today even on click does not stop the ads. I removed the extention and readded it hoping it would help, no luck, still getting ads.

### Screenshots

![Image](https://github.com/user-attachments/assets/a3296ff3-9dc0-400b-8c8f-b2ce02040459)

### Privacy

- [x] I agree to follow this condition

**Comment by leashadav** [comment]
still receiving ads

<img width="1351" height="852" alt="Image" src="https://github.com/user-attachments/assets/c41e3dc5-660a-4058-ad8a-a297295cea10" />

**Comment by Goldbricking** [comment]
> still receiving ads
> <img alt="Image" width="1351" height="852" src="https://private-user-images.githubusercontent.com/55554713/462942496-c41e3dc5-660a-4058-ad8a-a297295cea10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTE4MjY5NDgsIm5iZiI6MTc1MTgyNjY0OCwicGF0aCI6Ii81NTU1NDcxMy80NjI5NDI0OTYtYzQxZTNkYzUtNjYwYS00MDU4LWFkOGEtYTI5NzI5NWNlYTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzA2VDE4MzA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyMTRkODMxMjFlYTAxZDk4MzRlODc1M2M5NDY5Y2M1YzFiZDYxMTE2ZWE0NDkzMGVlNGE2MjMwNzFlMWNkYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1wdQHf2lITbx1IDLYaabDZdb-JjnSz98M1op-8EvsEQ">

Hey, I have tried it on Brave and it didn't work, but it worked on Librewolf... I don't really know why, but you might want to try it. 

I used the userscript with violentmonkey and it successfully blocks everything. Hope it get fix for Chromium Browsers though.

I hope this works for you in the meantime.

**Comment by kodiakhub** [comment]
@leashadav Is it Brave? If so, it's problematic. See: https://www.reddit.com/r/brave_browser/comments/1lj1ysu/comment/n1ggfsa/

Additional: If you're using Chrome or another browser. See: https://github.com/AdguardTeam/AdguardFilters/issues/187875#issuecomment-3040362852

The best way to use AdGuard Extra is via Violentmonkey.

**Comment by ghost** [comment]
Ads are still appearing as of today.

**Comment by kodiakhub** [comment]
@Spookeh-void What browser and extension(s)/userscript(s) are you using exactly? 🤔

AdGuard Extra was updated to version 1.0.700 recently.

**Comment by ynot01** [comment]
Running 1.0.700 on Violentmonkey and getting ads every single time, even on disabled cache

Firefox 140.0.2 (64-bit)

<img width="599" height="85" alt="Image" src="https://github.com/user-attachments/assets/b5b1cecd-4dbb-4b4e-b2ba-c945589ba809" />

**Comment by kodiakhub** [comment]
@AdamWr Could you please take a look? I noticed that ads appear when using Firefox with AdGuard Extra v1.0.700 via Violentmonkey. Just refreshing the page shows them. This doesn't happen with Chrome.

<details><summary>Screenshot</summary>
<p>

<img width="1920" height="1050" alt="Image" src="https://github.com/user-attachments/assets/0c76d19b-dba8-4081-9f5e-a569ea1f69fe" />

</p>
</details>



But looks like if we install AdGuard Extra extension it works, it's userscript issue for firefox. 🤔 

<details><summary>Screenshot</summary>
<p>

<img width="1920" height="1057" alt="Image" src="https://github.com/user-attachments/assets/4e3a8bbb-f34a-4c47-9872-65fe5f8e4626" />

</p>
</details>

**Comment by ynot01** [comment]
As a workaround, `video-swap-new` userscript at [pixeltris/TwitchAdSolutions](https://github.com/pixeltris/TwitchAdSolutions) works currently

**Comment by kodiakhub** [comment]
> As a workaround, `video-swap-new` userscript at [pixeltris/TwitchAdSolutions](https://github.com/pixeltris/TwitchAdSolutions) works currently

@ynot01 Can you test the AdGuard Extra extension on Firefox? It should work. See: https://github.com/AdguardTeam/AdGuardExtra?tab=readme-ov-file#firefox

**Comment by AdamWr** [comment]
The problem with not working userscript in Violentmonkey in Firefox should be fixed in version 1.0.701 (beta is already released, stable version will be available soon).
Thank you for reporting it.

**Comment by hugo9655** [comment]
im still getting preroll ads on 1.0.701 stable via the userscript. tested on firefox mobile with uBO

**Comment by AdamWr** [comment]
As far as I know, ads are blocked only on desktop version currently.

**Comment by hugo9655** [comment]
ah okay. ill use desktop for now

**Comment by AdamWr** [comment]
Though if only adding `m.twitch.tv` to the script is required, then I think we can do it.
I need to check it out.

<hr>

I have quickly tested it and it looks like that it works.

**Comment by gab854** [comment]
Tried 1.0.701 extension and userscript (not at the same time) with Brave Desktop. Adguard extension enabled as well.  
I'm getting prerolls at twitch.tv/twitchmedia2, twitch.tv/twitchmedia4, twitch.tv/twitchmedia25, twitch.tv/twitchmedia70, twitch.tv/twitchmedia71
Is it only working with Firefox Desktop atm?

**Comment by AdamWr** [comment]
It should works in Brave browser but only with userscript.
<details><summary>Screenshot</summary>

<img width="2559" height="1305" alt="Image" src="https://github.com/user-attachments/assets/98dc1127-4d09-454e-b0ba-6eb5689f5c2e" />

</details>

I'm not sure which user script manager do you use, but if it's `Tampermonkey`, then did you enable `Allow User Scripts` in extension settings?

<details><summary>Screenshots</summary>

<img width="2559" height="821" alt="Image" src="https://github.com/user-attachments/assets/fa267f37-c84d-4f42-b44a-2d4414cd183b" />


<img width="2559" height="1310" alt="Image" src="https://github.com/user-attachments/assets/eebc8d2c-2bb9-416b-8e49-499d4097bfb1" />

</details>

**Comment by gab854** [comment]
@AdamWr 

Was using ViolentMonkey but switched to Tampermonkey and enabled that option just now. 
I also deleted cache.
Same thing. I get that piano cat preroll.  
I'll try with another profile and report back.   

EDIT: Okay, so I messed up during this test. I was going to m.twitch.tv/twitchmedia2 instead of the desktop version.  
It's blocking ads perfectly now.

**Comment by AdamWr** [comment]
`m.twitch.tv` has been added in new version (`1.0.702`) which should be available now, or soon.
I have tested it in Chrome and Firefox, and it seems that ads are blocked correctly, at least on my device with userscript installed in AdGuard for Android.

**Comment by kodiakhub** [comment]
@AdamWr It works. 👍 

<details><summary>Screenshot</summary>
<p>

![Image](https://github.com/user-attachments/assets/845d2c7f-0e9c-4429-875b-3bc3739aaf66)

</p>
</details>

**Comment by hugo9655** [comment]
ty adam !

**Comment by akawshi** [comment]
Today I see ads on side bar. I'm using script with Tampermonkey and it seems to show up on any channel.
